### ISSUE TITLE
Returning a single instance

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#10]
Is there a way to register a dependency so that the same instance is injected every time? Without using a singleton that is.

**Comment by hmlongco** [comment]
In Resolver, you'd register the service in the .application scope.
```
register { MyService() }.scope(.application)
```
Resolver would then resolve it the first time it's needed but cache the result such that any further resolutions will get the same object.

For more, see the documentation for Resolver: Scopes.

**Comment by mycroftcanner** [comment]
That's amazing! Many thanks :)

**Comment by mycroftcanner** [comment]
It works.

I had to use `register { MyService() }.scope(Resolver.application)`

**Comment by hmlongco** [comment]
The shorthand works if you follow the practice of adding your registration blocks to Resolver.
```
extension Resolver {
    class func setupAccounts() {
        register { AccountListRepository<Account>([]) }.scope(shared)
        ...
     }
}
```
Then in your main injection file.
```
extension Resolver: ResolverRegistering {
    public class func registerAllServices() {
        setupAccounts()
        setupAccountDetails()
        ...
    }
}
```

**Comment by mycroftcanner** [comment]
Thanks... I just finished switching all my dependencies to Resolver!

All my init functions now look clean and shiny!! If you ever pop by London let me know I owe you a glass of wine or a beer!  I can't thank you enough!

p.s. One more question, is this the proper way to refer to previously registered service:

```
    register { CoreDataStack() }.scope(Resolver.application)
    register { (resolve() as CoreDataStack).context }.scope(Resolver.application)
```

**Comment by hmlongco** [comment]
As works. Or you can specify the type explicitly: resolve(CoreDataStack.self)

**Comment by patrickbdev** [comment]
Same as @mycroftcanner , I had to use Resolver.application. The shorthand `.application` wasn't recognised.

**Comment by mroushdy** [comment]
what about having some services rely on a single instance of a service and other services rely on another instance of that service?

**Comment by hmlongco** [comment]
> what about having some services rely on a single instance of a service and other services rely on another instance of that service?

You need to have some way to differentiate between the different services. That's usually when named services come into play.
