### ISSUE TITLE
defaultScope has erroneous type ResolverScopeGraph

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#11]
```swift
extension Resolver: ResolverRegistering {
    static func registerAllServices() {
        Resolver.defaultScope = Resolver.unique
        registerMyNetworkServices()
    }
}
```

> Cannot assign value of type 'ResolverScopeUnique' to type 'ResolverScopeGraph'

**Comment by mycroftcanner** [comment]
I tried:

```
        Resolver.defaultScope =  ResolverScopeUnique()
```
> 'ResolverScopeUnique' initializer is inaccessible due to 'internal' protection level

**Comment by hmlongco** [comment]
See the version on develop which fixes this. Also, you need to make sure that you know what you're doing if you change the default scope to unique. Using the graph scope to cache objects during the same resolution cycle is standard practice on most DI systems.

**Comment by mycroftcanner** [comment]
@hmlongco You are right, I am going to use that scope for my singletons (not exactly singletons as I got rid of all my shared singletons and I was using a [dependency container](https://www.swiftbysundell.com/articles/dependency-injection-using-factories-in-swift/) until I started using Resolver.

**Comment by hmlongco** [comment]
So one final note is the the default scope is what's used if you didn't specify a scope for a given registration. If you do `register { MyService() }.scope(.application)` Then during a resolution cycle everything uses the graph scope except when MyService() is resolved, which is cached as a singleton in the app scope.

**Comment by mycroftcanner** [comment]
@hmlongco oh wait ...  I just pasted the example from the documentation.  I was never using unique... I meant I was using `.application`

Thanks for the tips though
