### ISSUE TITLE
cachedServices is not thread safe

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#12]
Any chance you could make the application cache thread safe?

In general I only let the strict necessary on the main thread and I use Texture so everything runs in the background except for strict UIKit and some SwiftUI stuff

Maybe implementing a lock on the cachedServices would help:

```
            cachedServices[registration.cacheKey]
```

**Comment by hmlongco** [comment]
You mean like using mutex to do thread locking?

```
    public final func resolve<Service>(resolver: Resolver, registration: ResolverRegistration<Service>, args: Any?) -> Service? {
        pthread_mutex_lock(&mutex)
        defer { pthread_mutex_unlock(&mutex) }
        if let service = cachedServices[registration.cacheKey] as? Service {
            return service
        }
        let service = registration.resolve(resolver: resolver, args: args)
        if let service = service{
            cachedServices[registration.cacheKey] = service
        }
        return service
    }
```

**Comment by hmlongco** [comment]
I might mention that if you're using Resolver in a project it might be worth your while to spend the 15-20 minutes it would take to read the documentation... ;)

> Further, Resolver:
> Is tested in production code.
> Is thread safe (assuming your objects are thread safe).
> Has a complete set of unit tests.
> Is well-documented.

**Comment by mycroftcanner** [comment]
Sorry about that... I am so used to project not using mutex or barriers... 

I just assumed or was tired as it was right in front of my eyes.

**Comment by mycroftcanner** [comment]
I had a bad access on cachedServices[registration.cacheKey].

I didn't investigate and just assumed. A quick fix was to call the registration early.

Now I can't reproduce the problem. What do you think could have caused a bad access on cachedServices?

**Comment by mycroftcanner** [comment]
Finally managed to reproduce the issue:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/55385694/68072819-32bbe680-fd8a-11e9-8aa5-752a9426b7cd.png">


<img width="402" alt="image" src="https://user-images.githubusercontent.com/55385694/68072817-2a63ab80-fd8a-11e9-8d14-4ce0206c16ba.png">

@hmlongco any ideas what would be the cause?

**Comment by mycroftcanner** [comment]
The factory instance is injected in my SceneDelegate:

```
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    @Injected private var auth: Auth
    @Injected private var factory: WindowFactory
```

then my environment objects are injected inside the Factory class:

```
    // Used a EnvironmentObjects in SwiftUI view hierarchies
    @Injected private var auth: Auth
    @Injected private var settings: SettingsStore
```

Is there a race condition or am I doing something wrong?

**Comment by mycroftcanner** [comment]
@hmlongco ??

**Comment by hmlongco** [comment]
Download and try the develop branch. I added locking around the registerAllServices call. Also I'm not sure what injection code you're using as that's been updated as well.

**Comment by mycroftcanner** [comment]
thanks I'll try

**Comment by mycroftcanner** [comment]
I can't find the @Injected property wrapper in this repo I am using the code in your blog post.

>We couldn’t find any code matching 'propertyWrapper' in hmlongco/Resolver

**Comment by hmlongco** [comment]
@Injected (and @LazyInjected) is in the develop branch at the moment.

**Comment by mycroftcanner** [comment]
I am still encountering random crashes... have you tried using a dispatch queue barrier instead of a pthread mutex?

**Comment by mycroftcanner** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/55385694/70944976-775ac300-2054-11ea-88ef-3a78c10b50b5.png">

**Comment by hmlongco** [comment]
Checkout the develop branch. I think it helps if the mutexes are initialized... :(


On Dec 16, 2019, at 3:36 PM, Mycroft Canner <notifications@github.com> wrote:

 <https://user-images.githubusercontent.com/55385694/70944976-775ac300-2054-11ea-88ef-3a78c10b50b5.png>
