### ISSUE TITLE
No such module 'Resolver'

### ISSUE THREAD

**Issue by VictorVarLed** [hmlongco/Resolver#121]
Hi. I was trying to add Resolver in a new iOS project using SPM. The SPM detects Resolver, Resolver-Dynamic and Resolver-Static. After adding those three to my project when I try to import Resolver in a file I see - > "No such module 'Resolver'"

What am I doing wrong? Thank you

**Comment by hmlongco** [comment]
Can't really hep with this as not using SPM.

**Comment by haemi** [comment]
@VictorVarLed did you find a solution?

**Comment by PierreCapo** [comment]
I don't think you should add the 3 products Resolver, Resolver-Dynamic and Resolver-Static. Just pick the one you want and it should work. Like for instance if you want to use Resolver as a dynamic framework, just link with `Resolver-Dynamic`.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/26744253/222721904-8280f005-75b1-4203-8540-262f9dc684f5.png">
