### ISSUE TITLE
1.4.4 not available through Cocoapods

### ISSUE THREAD

**Issue by nashfive** [hmlongco/Resolver#125]
Hi @hmlongco ! Kudos on the lib, I like it a lot 👍🏻 
I am trying to use the latest version 1.4.4 in my project, but pod doesn't seem to find the latest version 1.4.4 in the repo. 

I tried in an empty project to add just the Resolver pod without specifying a version, then with "1.4.4" and then "~> 1.4.4", but none of my `pod update` managed to retrieve anything.
```
[!] CocoaPods could not find compatible versions for pod "Resolver":
  In Podfile:
    Resolver (~> 1.4.4)

None of your spec sources contain a spec satisfying the dependency: `Resolver (~> 1.4.4)`.
```

Is it just me ?

**Comment by svycka** [comment]
because it is not released yet?

**Comment by nashfive** [comment]
Ha it makes sense ;) I forgot that pods were released manually... 
Not sure why it's not released yet though.
