### ISSUE TITLE
ResolverRegistering registration vs local registration question

### ISSUE THREAD

**Issue by JonLz** [hmlongco/Resolver#13]
I was a little surprised that if I register something "globally" via implementing `ResolverRegistering` and then register it again locally, the global registration still wins. I proved that with a [test that demonstrates the ordering](https://github.com/JonLz/Resolver/pull/1/files). 

My question is if this is correct or if I'm thinking about the ordering here the wrong way or there is a better way to do this.  For context I'm trying to figure out the best way to go about registering a different set of implementations for a test target. I'd like to be able to do something like registering production implementations in my main target using `ResolverRegistering` and then register mock implementations in my test target by overriding the registration by calling something like `Resolver.register(TestImplementation()).implements(Protocol.self)`.

As an aside, I also wonder if you have thoughts around a different approach to resolving implementations in a test target. What if something like a `ResolverOverrideRegistering` protocol existed that could be implemented in a test target only that would then be called after `ResolverRegistering` was checked to override any implementations needed for testing? Because in my current project I don't have a good way to even hook into local overrides as described above and would prefer to do so globally.

Thanks for the nice library.

**Comment by JonLz** [comment]
So I found some support for this in reading more carefully through the [docs](https://github.com/hmlongco/Resolver/blob/master/Documentation/Containers.md#nested-containers). I still wonder if there isn't a more ergonomic way to create containers across targets though? With this I still need do all the work within the same `registerAllServices()` function in my main target. I think it'd be clearer to have mock registration happen in a different method (and altogether different target).

Relatedly, I wonder if registration of services should happen _before_ calling `resolve`. Consider the case of calling `Resolver.root` from a property wrapper. `Resolver.root` would resolve to `Resolver.main` _before_ we can change the instance via the `root = mock` per the example in the docs. If the `registerAllServices` method got called as part of initialization I think this could all be avoided.

What do you think?

**Comment by hmlongco** [comment]
Did you look at the documentation for containers?

https://github.com/hmlongco/Resolver/blob/master/Documentation/Containers.md

**Comment by hmlongco** [comment]
So given this code...
```
import SwiftUI

protocol MyTestClassType {
    func value() -> String
}

class MyTestClass: MyTestClassType {
    func value() -> String {
        return "Test"
    }
}

extension Resolver: ResolverRegistering {
    static public func registerAllServices() {
        register { MyTestClass() as MyTestClassType }
    }
}

class ContentViewModel {
    @Injected var test: MyTestClassType
}

struct ContentView: View {
    var viewModel = ContentViewModel()
    var body: some View {
        Text(viewModel.test.value())
    }
}
```
One can create the following in test...

```
import XCTest
@testable import ResolverResolutionTest

class MockTestClass: MyTestClassType {
    func value() -> String {
        return "Mock"
    }
}

class ResolverResolutionTestTests: XCTestCase {

    override func setUp() {
        let mock = Resolver(parent: Resolver.main)
        mock.register { MockTestClass() as MyTestClassType }
        Resolver.root = mock
    }
    
    func testExample() {
        let model = ContentViewModel()
        XCTAssertTrue(model.test.value() == "Mock")
        XCTAssertFalse(model.test.value() == "Test")
    }

}
```

**Comment by hmlongco** [comment]
Checkout the current version of Resolver in develop. It's updated such that calling Resolver.resolve will hit the correct root (should it be updated in registerAllServices). Same for injected.

**Comment by JonLz** [comment]
Thanks for the feedback and links! I will check this out and let you know if it fixes those issues. I think the examples you provided for setting up the mocks looks great. I was always wondering what the use case was for the initializer that took a parent resolver. 

The one thing that might still be nice to look into is how we could achieve similar behavior provided by `registerAllServices` in a different target. As mentioned above because `registerAllServices` is a method that will be defined in the main target, we have to write code in that method to deal with setting up a mock instance and registering mock instances (which might not even be available in the main target but in a test target only). 

I think that it would be nice to invest in a way to register a set of mocks in code that lives only in a test target. That way `registerAllServices` remains cohesive to setting up dependencies for the main target and setting up mocks can reside within the test target. I think that in reality a lot of use cases for DI are to replace a set of production services with mocks and in practice a lot of the time those mocks might look the same across a lot of unit tests (`MockLogService`.. `MockAnalyticsService`.. `MockNetworking` etc etc.). It would be nice to do this once and not in every unit test or in a base test class (not all apps have a base test class)

Now that you've addressed some of the issues between root / main instances resolution I'll see if I can crack open a PR to investigate how this might look.

**Comment by hmlongco** [comment]
If you look at the following you'll see you can register a class that's run before all of the test bundles are executed. You could put the one time mock setup / root swap method there.

https://developer.apple.com/documentation/xctest/xctestobservationcenter
