### ISSUE TITLE
Can't change defaultScope

### ISSUE THREAD

**Issue by sdgroot** [hmlongco/Resolver#14]
Because the `defaultScope` property has no explicit type definition, it's implicitly typed as the default value, which is `ResolverScopeGraph`. This makes it impossible to set it to a different scope, e.g. `Resolver.application` as this causes the following error: **Cannot assign value of type 'ResolverScopeApplication' to type 'ResolverScopeGraph'**.

To fix this issue, `defaultScope` should be typed as `ResolverScope`.

Thanks for this otherwise great little lib, and the accompanying Medium post, which brought me to using this along with the property wrapper :)

**Comment by hmlongco** [comment]
If you pull the development branch it's been fixed there.

**Comment by sdgroot** [comment]
Great thanks!
