### ISSUE TITLE
Value types in Graph scope

### ISSUE THREAD

**Issue by totidev** [hmlongco/Resolver#143]
When using `ResolverScopeGraph`, only classes are cached. However, if you use `ResolverScopeCache`, then value types are also cached. Is there any reason for this difference? Graph is supposed to reuse services in a given resolution cycle - except this would only apply to classes, and value types would be created multiple times.

**Comment by hmlongco** [comment]
Think that was just an oversight. How heavy are your value types?

**Comment by totidev** [comment]
Not heavy at all - was just curious if there had been a reason for the difference. Thanks for answering.
