### ISSUE TITLE
No such file or directory: ... Resolver-Dynamic.framework/Resolver-Dynamic

### ISSUE THREAD

**Issue by DullingWine** [hmlongco/Resolver#146]
Hi
First time user of resolver here. I installed the package via xcode package manager, wrote some IoC and tried to build. I get:

clang error: no such file or directory: '..../PackageFrameworks/Resolver-Dynamic.framework/Resolver-Dynamic'

any idea how to fix this?

**Comment by DullingWine** [comment]
Just for completeness here:
- When adding via the package manger, i saw Resolver, Resolver-static and Resolver-dynamic. I selected all 3.
- I only see one package in the package dependencies (Resolver)
- I am try to run on a simulator.
- intel mac mini
- I tried deleting the package, and adding - same result.

**Comment by jeantuffier** [comment]
I'm running in the exact same issue.

**Comment by hmlongco** [comment]
When I add it to a project I usually only select the "Resolver" option. Not an expert on package manager.

**Comment by hmlongco** [comment]
Just pick one. Picking all of them confuses Xcode.
