### ISSUE TITLE
How to inject cycle reference objects?

### ISSUE THREAD

**Issue by alexlee002** [hmlongco/Resolver#15]
E.g.:

```swift
class Parent {
    var child: Child?
}

class Child {
    init(parent: Parent) {}
}
```

**Comment by hmlongco** [comment]
So, I can see what you're doing, but the code sample lacks context. I've never run across a situation where you'd have parent/child cross-references in a service architecture. In data, yes. But as a general rule you don't use dependency injection to inject data. Services, managers, view models, yes. Data, no.

**Comment by hmlongco** [comment]
So, given the following...
```
class ClassA {
    @Injected var b: ClassB
}

class ClassB {
    weak var a: ClassA?
}
```
You can resolve the cyclic dependency in registration using resolveProperties...
```
register { ClassA() }
    .resolveProperties { (_, a) in
        a.b.a = a
    }
register { ClassB() }
```
And with an upcoming version of Resolver....
```
class ClassP {
    @Injected var c: ClassC
}

class ClassC {
    @LazyInjected var p: ClassP
}
```
With registration like...
```
        register { ClassP() }.scope(shared)
        register { ClassC() }
```
