### ISSUE TITLE
using InjectedObject as a StateObject

### ISSUE THREAD

**Issue by murad1981** [hmlongco/Resolver#151]
I couldn't find a way to use the `@InjectedObjected` property wrapper to act as a `@StateObject` in the view, after I checked the docs it turned out that `@InjectedObject` is actually an `ObservedObject`. 

is there a way to inject an observable object in a `SwiftUI` view  to act as a `@StateObject` ?

**Comment by murad1981** [comment]
yeah this makes sense, however, in the last `struct` in Resolver package, at the line: `@ObservedObject private var service: Service` i guess it's possible to replace `@ObservedObject` with `@StateObject` to get its goodies.

**Comment by hmlongco** [comment]
As is the system works with iOS 13. Utilizing @StateObject in they way would make the minimum iOS 14.

To me they better choice is to simply not use @InjectedObject for view models and just use @StateObject. Use @Injected in the view model for any view model specific dependencies.

See: https://betterprogramming.pub/swiftui-view-models-are-not-protocols-8c415c0325b1

**Comment by murad1981** [comment]
I've read the cool article, which I almost done the same in my codebase, i'd also prefer using `@StateObject` for the view model when I reference it in the view struct, and I use `@Injected` for view model's dependencies such as data loaders. What mixes things up with me is a common setup like this one:

```
import SwiftUI
import Resolver


struct Category {
    var id: Int
    var name: String
}

protocol DataLoader {
    func loadData(categoryId: Int) async
}

struct ContentView: View {
    var categories = [Category(id: 1, name: "cat1"),
                      Category(id: 2, name: "cat2")]
    
    var body: some View {
        List {
            ForEach(categories, id: \.id) { category in
                CategoryDetailsView(vm: ViewModel(categoryId: category.id))
            }
        }
    }
}

struct CategoryDetailsView: View {
    @ObservedObject var vm: ViewModel
    
    var body: some View {
        VStack {
           // ... display data returned by viewModel's getData method
        }
        .task {
            await vm.getData()
        }
    }
}

class ViewModel: ObservableObject {
    @Injected private var loader: DataLoader
    var categoryId: Int
    
    init(categoryId: Int) {
        self.categoryId = categoryId
    }
    
    func getData() async {
        await loader.loadData(categoryId: categoryId)
    }
}
```

when the view model depends on external dependencies, such as an `id`, in this case I can't do something like:
`@StateObject private var vm = ViewModel()` or even `@StateObject var vm: ViewModel` because Apple recommends that `@StateObject` should be instantiated and owned by the view itself in opposite to `@ObservedObject` which's fine to be injected from outside the view like in the above case.

what should be the best choice for the above case ?

**Comment by hmlongco** [comment]
```
struct ContentView: View {
...
            ForEach(categories, id: \.id) { category in
                CategoryDetailsView(categoryId: category.id)
            }
...
}

struct CategoryDetailsView: View {
    let categoryId: Int
    @StateObject var vm = ViewModel()
    var body: some View {
        VStack {
           // ... display data returned by viewModel's getData method
        }
        .task {
            await vm.getData(categoryId)
        }
    }
}

class ViewModel: ObservableObject {
    @Injected private var loader: DataLoader    
    func getData(_ categoryId: Int) async {
        await loader.loadData(categoryId: categoryId)
        // then do something with data
    }
}
```
Constructing the VM in the initializer is a bad thing. Using them as ObservedObjects is also a bad thing. Especially if something can trigger your content view to recompute state (even, say, a device rotation or dark mode).

At the risk of boring you to tears ;) I might suggest another article in order to understand why.

https://medium.com/swlh/deep-inside-views-state-and-performance-in-swiftui-d23a3a44b79

**Comment by hmlongco** [comment]
Glad you liked the article. Keep in mind that it's almost two years old and that my view of "best practices" has changed somewhat since that article was written.

Note when I refactored your code I changed the view like so.
```
struct CategoryDetailsView: View {
    let categoryId: Int
    @StateObject private var vm = ViewModel()
    var body: some View {
        VStack {
           // ... display data returned by viewModel's getData method
        }
        .task {
            await vm.getData(categoryId)
        }
    }
}
```
Here we create the view model in the state object. (I just added the private.) I can do this because I no longer create the VM with categoryId in the initializer, but instead use the task modifier to pass it in to the one function that needs it. The getData function's signature changed accordingly.
```
    func getData(_ categoryId: Int) async {
        await loader.loadData(categoryId: categoryId)
        // then do something with data
    }
```
This keeps all of the initializers lightweight, as the @StateObject isn't actually created until the view body is invoked. And we don't want to start working on the load until the view is actually presented.

It also lets SwiftUI be SwiftUI.

**Comment by murad1981** [comment]
This is a good workaround, but in a larger scenario I think we may stick with injecting the parameters using the initializer.

Is there an answer from `Resolver` to my last question in last paragraph in the previous comment, which was:

... and this opens a new question related to `Resolver`: if I decided to use `@InjectedObject` for the view model that expects a parameter (like an` id` or `item` in the above example), how can I register it in `registerAllServices` method ? and do I need to pass it from the `NavigationLink` like what you did in the piece of code above ?

**Comment by hmlongco** [comment]
If you're going to pass the parameter in the initializer as mentioned then there's no need to register it as it can't be injected. There's no way to get the id into the process.

Just pass it into a StateObject.

**Comment by murad1981** [comment]
I've worked recently on Flutter, they have a package called: `Get` which's responsible for injection, it's possible to register a class for the view model at the launch of the app even if it takes another dependency, like this:
```
GetIt.instance.registerFactoryParam<MyViewModel, SomeModel, void>(
          (param1, _) => MyViewModel(model: param1));
```

where `param1` or `paramN` is a reserved keyword in the package for this scenario.

 when the user taps a row in the list to open its details, we use this line:

```
ItemScreen(model: item)
```
and in the `ItemScreen`'s `init` method we do the following:

```
_viewModel = GetIt.instance<MyViewModel>(param1: model);
```

**Comment by hmlongco** [comment]
Just noting that StateObject thunk initializer captures the parameter in an autoclosure, so the VM won't be created until the view body is accessed for the first time.

**Comment by murad1981** [comment]
If you have a long form that consists of more than one screen: Step1View, Step2View, Step3View, SummaryView 
do you recommend creating one `StateObject` for the `FormViewModel` ? that `FormViewModel` handles user input validation,  UI rendering logic and storing user input into a `Codable` model to be submitted to the API at the end.

**Comment by hmlongco** [comment]
That's getting outside of Resolver and my answer would be "it depends" on the complexity of the individual views. Alternative is a specific VM for each screen (if needed) and a common repository/manager for the overall logic.
