### ISSUE TITLE
I have yet to see my videos

### ISSUE THREAD

**Issue by spikeb4** [hmlongco/Resolver#158]
I have yet to see my videos 

_Originally posted by @Spikebady in https://github.com/ossf/scorecard/pull/2030#pullrequestreview-1033477089_

**Comment by hmlongco** [comment]
I suggest you read the README.

**Comment by hmlongco** [comment]
I have no idea what video you're referring to. This project is a Swift dependency injection library and has nothing to do with imaging or video.

There are almost 24,000 projects on GitHub that reference resolver...

https://github.com/search?q=resolver

**Comment by Spikebady** [comment]
I really need help getting that video back.

**Comment by majie776** [comment]
这是来自QQ邮箱的自动回复邮件。
 
邮件已收到

**Comment by hmlongco** [comment]
Again, I have no idea what video you're referring to. This project is a Swift dependency injection library and has nothing to do with imaging or video.
