### ISSUE TITLE
Unknown attribute 'Injected'

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#16]
I checked that Swift 5 is correctly selected in my target and in pods.

I have correctly configure the development the version in my Podfile:

```
	pod 'Resolver', :git => 'https://github.com/hmlongco/Resolver', :branch => 'develop'
```

<img width="299" alt="image" src="https://user-images.githubusercontent.com/55385694/70388857-6d2f2980-19af-11ea-8b08-84272cfe41cd.png">

still I get :

```
Unknown attribute 'Injected'
```

**Comment by mycroftcanner** [comment]
Nevermind... before you included `@Injected` I was using the one from your blog post so I didn't need to import Resolver and now I do

**Comment by diego-lipinski-de-castro** [comment]
Even importing Resolver I get this error

**Comment by seanthegoudarzi** [comment]
Make sure that you are actually getting the Resolver version with property wrappers. A cause could be the "platform" entry at the top of your pod files.
Changing to this helped me get the version with @propertyWrappers

`platform :ios, '13.0'`

**Comment by itsmeneartou** [comment]
@diego-lipinski-de-castro Were you able to resolve the error?
@seanthegoudarzi I did this but still I am receiving the error.
Any help?
