### ISSUE TITLE
Bad Access when registering with latest develop branch

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#17]
I haven't change anything in my code and I get :

<img width="867" alt="image" src="https://user-images.githubusercontent.com/55385694/70388970-1296cd00-19b1-11ea-9caa-78cba4b4da8b.png">

when registering my dependencies.

**Comment by mycroftcanner** [comment]
It seems that cycling dependencies creates an infinite loop. It used to work without issues before

**Comment by mycroftcanner** [comment]
Switching to @LazyInjected fixes the problem.

The old @Injected code from your blog didn't have that problem.

**Comment by hmlongco** [comment]
The old injected code did lazy injection which meant that your object needed to be mutable. It also meant that Injected couldn't be used in SwiftUI views. It also meant graph dependencies didn't work as expected.

The new Injected resolves as soon as it's instantiated, which fixes those problems.

And yes, you can use LazyInjected to resolve cyclic dependencies, but be aware that you may be creating strong retain cycles.

See: https://github.com/hmlongco/Resolver/blob/master/Documentation/CyclicDependencies.md
