### ISSUE TITLE
[FR]: Support for Apple Privacy Info Manifest-Files

### ISSUE THREAD

**Issue by faken** [hmlongco/Resolver#175]
Apple will enforce the requirement for a privacy info manifest file for all third party libraries this year.
More information can be looked up here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
The library needs to be updated to include a privacy info manifest-file

**Comment by observableobject** [comment]
@hmlongco any update on this?  it should be quite easy to generate.

**Comment by hmlongco** [comment]
I'll probably just borrow the one from Factory. But keep in mind the notice at the top of the README file...

**Note: Later in 2023 Resolver will be deprecated and replaced by my new dependency injection system, [Factory](https://github.com/hmlongco/Factory). Factory 2.0 is a true container-based dependency injection system that's compile-time safe and is smaller, lighter, and faster than Resolver. As good as Resolver is, Factory is better.**

**Comment by dotswift** [comment]
Glad to hear this @hmlongco , really appreciate all the work on Resolver.

I'll be migrating to Factory, but this manifest will be clutch in the meantime.

🫡

**Comment by amarkotic** [comment]
@hmlongco will privacy manifest be generated for Resolver at all?

**Comment by hmlongco** [comment]
Pushed 1.5.1.

**Comment by evilutioner** [comment]
Privacy manifest integration should be by itegrate as resource_bundles. This way of integrations cause the conflict with projects PrivacyInfo file.
