### ISSUE TITLE
Best practices: multiple application flows

### ISSUE THREAD

**Issue by SolorzanoJose** [hmlongco/Resolver#19]
Let's say you have an application following the MVVM+C architecture, what are the best practices to implement DI with resolver in the following scenario: 

1. There's a root coordinator with some dependencies.

2. Child coordinators need to be passed some of the dependencies from the root coordinator.

3. A particular coordinator 

I've been reading the documentation and I think I should be leveraging multiple containers + different scopes but the big picture is still not very clear.

Mainly, how can I share dependencies between the root coordinator and each child, and further add different dependencies for each child coordinator without my code becoming hundreds of repeated registration lines (root coordinator passing dependencies to the child coordinator and then registering their own)

And a bonus question, how can I inject a dependency that is dynamically dependent on a parameter? Let's say, for example, a view model with a specific model id.

Thanks!

**Comment by SolorzanoJose** [comment]
For the bonus question, I guess I'm thinking of something like "resolve(with : Parameters)" , which additionally injects parameters to the resolved instance. A specific use case is a view model that needs to know a specific model id.

**Comment by hmlongco** [comment]
Easiest first. Resolver supports passing arguments into the registration block.

https://github.com/hmlongco/Resolver/blob/master/Documentation/Arguments.md

As to the first question, it may help to read my article on Modern Dependency Injection in Swift, with focus on injecting services, not data, plus the section on shared scopes.

https://medium.com/better-programming/modern-dependency-injection-in-swift-952286b308be?source=friends_link&sk=ca214e3fede014d4d9528811e7204a40
