### ISSUE TITLE
Multiple arguments instead of single parameter 

### ISSUE THREAD

**Issue by ahmadmssm** [hmlongco/Resolver#21]
I can not seem to find a ways to pass multiple arguments to an injected Service

**Comment by hmlongco** [comment]
If you're passing a lot of values I'd say you probably need to break the object out into a repository or service architecture, or at least define a model with those values.

Short-term, you can always build a dictionary and pass 'em in that way.

**Comment by ahmadmssm** [comment]
Thanks, but it dosen't make sense because for example if i need to inject a presenter which accepts 2 params from a view controller, user id and view  controller mode for example, so the only option i have here is to pass it as an array, dictionary or tuble and i have to unbox it in the constructor of the presenter.
Koin which is a well known DI library in Android and very similar to your library allows passing up to 5 params.

Anyways, I wrote an extension function to let your library support passing multiple params, not just 5. 

can i open a PR with this feature and you release a new version with this new feature.

**Comment by hmlongco** [comment]
Can you show me the extension function?

**Comment by ahmadmssm** [comment]
@hmlongco
I forked the repo and added the feature and there is a pull request opened with this feature.
I have also added unit tests and documentation.
I hope you release a new version with this feature :D.
Thank you..

**Comment by ahmadmssm** [comment]
@hmlongco any comments ?!

**Comment by hmlongco** [comment]
Commented on PR. Appreciate the work, but implementation not merged.

**Comment by ahmadmssm** [comment]
@hmlongco Please check my comments on the PR.
We are using Resolver recently in multiple projects but we are not happy with arguments passing implementation.
