### ISSUE TITLE
Swift Compiler Error Group

### ISSUE THREAD

**Issue by zarochintsev** [hmlongco/Resolver#27]
Hi, I have a bug when I want to archive my application. Resolver v1.1.1.

<img width="648" alt="Screenshot 2019-12-28 at 13 48 10" src="https://user-images.githubusercontent.com/5650844/71543154-b18f6300-2978-11ea-8303-702510462411.png">
<img width="1659" alt="Screenshot 2019-12-28 at 13 47 07" src="https://user-images.githubusercontent.com/5650844/71543156-b5bb8080-2978-11ea-9f84-57dc310ea151.png">

**Comment by Pilzbauer** [comment]
Same issue here.

**Comment by th-mustache-dk** [comment]
+1

**Comment by Pilzbauer** [comment]
I found a workaround by setting the iOS deployment target to at least iOS 11

**Comment by hmlongco** [comment]
Looks as if it starts complaining on a deployment target less than that of iOS 11.

I don't see a workaround for this, so I updated the project accordingly. If you want/need to support iOS versions earlier than iOS 11, then you need to add Resolver directly to your project and delete the InjectedObject property wrapper.

**Comment by zarochintsev** [comment]
@hmlongco  Thank you!

**Comment by hmlongco** [comment]
More notes in the [installation guide](https://github.com/hmlongco/Resolver/blob/master/Documentation/Installation.md).
