### ISSUE TITLE
Feuture: Property wrapper for optionals

### ISSUE THREAD

**Issue by th-mustache-dk** [hmlongco/Resolver#28]
I don't know if it is even possible but it could be nice to do this.

    @InjectedOptional
    fileprivate var service: SomeServiceType?

**Comment by hmlongco** [comment]
It's possible, but how would it be different from LazyInjected? With LazyInjected the service isn't loaded until it's first referenced. If it's never referenced, it's never loaded.

Or is it your idea that the injection fails if the object was never registered? Under what circumstance would you conditionally register a service?

Just trying to understand the use case.

**Comment by th-mustache-dk** [comment]
I have created a small networking library which has a service that the users must implement. Right now its mandatory to implement this service but I would like to make it optional.

**Comment by hmlongco** [comment]
Merged PR with OptionalInjected
