### ISSUE TITLE
[HELP] Different Resolver in production, mock, testing, etc..

### ISSUE THREAD

**Issue by bentsen** [hmlongco/Resolver#30]
Hi,

New player with Resolver, I wonder what is the right solution to have different injectors depending on execution context.

In release, I plan to use what is recommended:
 ```swift
Resolver: ResolverRegistering
``` 

For my unit tests I need to inject different classes. 

Ex: 
**Production:** 
```swift
register { AccountsAPI() as AccounstAPIProtocol }.scope(application)
 ```

**Unit test:** 
```swift
register { MockAccountsAPI() as AccountsAPIProtocol }.scope(application)
 ```

When performing unit tests or UI tests, the idea is not to inject the classes used in production.

How would you do that?

**Comment by hmlongco** [comment]
Read the section on [nested containers](https://github.com/hmlongco/Resolver/blob/master/Documentation/Containers.md).

You can let registerAllServices run in your application, but swap out the root for a "test" container that contains your mock registrations for unit tests.

You could also look at the "mocking data" section in the documentation on [names](https://github.com/hmlongco/Resolver/blob/master/Documentation/Names.md) if you want to run an app in production mode vs mock mode.

**Comment by bentsen** [comment]
@hmlongco 
Thanks !
I’ll take a look.
