### ISSUE TITLE
Register more than one dependency for a given protocol

### ISSUE THREAD

**Issue by SolorzanoJose** [hmlongco/Resolver#32]
Lets say I have a class that needs a list of dependencies conforming to `Loggeable`, how do I go about injecting these dependencies if they all conform to the same protocol? What I found is that the last registration overwrites all other

**Comment by SolorzanoJose** [comment]
Reminder

**Comment by mgray88** [comment]
Have you tried using [names](https://github.com/hmlongco/Resolver/blob/master/Documentation/Names.md)?

Seems like it would fill your needs

**Comment by hmlongco** [comment]
```
class Dependency: Loggable { ... }

class ViewModel {
init(log: Loggable) { .. }
}

register { Dependency() }
register { ViewModel(log: resolve(Dependency.self) }
```

As far as the view model is concerned it's just getting a Loggable whereas in the registration you're explicitly defining the the type of luggable it should receive.
