### ISSUE TITLE
Create a method to unregister all service registrations

### ISSUE THREAD

**Issue by patrickbdev** [hmlongco/Resolver#43]
An example of this could be 
```
func unregisterAll() {
    registration = [Int : [String : Any]]()
}
```

This would be useful when running Unit Tests and wanting to reset the registrations between each test.

**Comment by hmlongco** [comment]
This only works if you force all unit tests to run sequentially and not in parallel. Otherwise test B could blow away dependent services setup by test A.

**Comment by patrickbdev** [comment]
Yep, it would require that.

**Comment by hmlongco** [comment]
Added Resolver.reset()

**Comment by patrickbdev** [comment]
Perfect, thanks a lot!
