### ISSUE TITLE
Multiple Arguments

### ISSUE THREAD

**Issue by hmlongco** [hmlongco/Resolver#44]
So I'm thinking about providing support for multiple arguments in Resolver. I'm not a big fan of the concept but several people have asked for it.

Currently, you can pass in a single argument of type Any? that you then unpack from the second argument in the registration factory.
```
register { (_, arg) -> SomeService in
            let mode: Int = arg as! Int
            SomeService(mode)
        }

let service: SomeService = resolver.resolve(args: true)
```
Now, you can pass multiple arguments today by creating a custom struct or throwing items into a dictionary, but unpacking the Any? type in the factory is clunky.

With multiple argument support baked directly into Resolver, you basically provide more than one argument in a positional format.
```
let service: XYZEditService = resolver.resolve(arg0: true, arg1: "Fred")
```
The issue lies in consuming those arguments in the registration factory. With multiple argument support, I'm basically creating a struct that you can easily unpack via subscript to get at the typed arguments.

The first (and easiest) approach would simply require the user to "create" the new structure from the existing argument parameter if they want or need multiple arguments.
```
register { (_, args) -> XYZEditService in
            let args = ResolverArgs(args)
            return XYZEditService(editing: args[0]!, name: args[1]!)
        }
```
Again, this would be easiest to support, but seems a bit clunky in that in order to use it you always have to translate args into ResolverArgs. On the plus side, this mechanism doesn't break existing code, but on the flip side with multiline factory functions you often end up having to explicitly specify the factory return type. Another minus.

The second approach would be to add another factory variant in which I could simply create and pass ResolverArgs directly. To use it you'd just "skip" the old set of args and access the new set of multiple arguments. 

Note in the following example the new "args" are now passed as the third parameter slot, not the second as before.
```
register { (_, _, args) in
        XYZEditService(editing: args[0]!, name: args[1]!)
        }
```
It's quite a bit cleaner, but for some reason having two different argument parameters bugs me. 

The major benefit is that again, it doesn't break existing registration factories that might be using the existing arguments parameter. One other negative is that the code for this is a bit more complex.

So, as the final solution I could simply replace the old arguments parameter with the new one and be done with it. 
```
register { (_, args) in
        XYZEditService(editing: args[0]!, name: args[1]!)
        }
```
In other words, this is how both single and multiple argument parameter passing work in Resolver from this point forward. Pass in arguments, and they're provided to the factory as ResolverArgs. Period. 

The major drawback being, of course, that this change breaks existing code.

Now, I can promote the old "args" argument automatically and make it available as the first argument in the new array, but you'd still need to change the code to access it...
```
register { (_, args) in
            let mode: Int = args[0]!
            SomeService(mode)
        }
```
All in all, I'm definitely leaning towards the later approach, but again, it has the drawback of breaking existing code. 

So... any thoughts? Is a clean feature desirable enough to warrant breaking existing code? At what point do you simply bite the bullet and move forward?

**Comment by ahmadmssm** [comment]
Actually I like the idea of the third parameter and I agree with you that adding a boatload of argX functions to the Resolver class and static class definitions is not a good idea, but it was the simplest, fastest and the cleanest way to achieve what i want, So, yes I like the new approach.
The only thing I see that can be better is the ability to get the arguments using this syntax arg0(), arg1(), ... instead of args[index] because the first one is more cleaner and the second one is more error-prone.
So I would say, go ahead with the new implementation, It will be a major improvement for your library.
Thank you very much for considering my suggestion and solution.

**Comment by ahmadmssm** [comment]
@hmlongco Let me know your openion please

**Comment by hmlongco** [comment]
So I worked on the issue and the result is now in the develop branch.

You can read about the new argument syntax here....

https://github.com/hmlongco/Resolver/blob/develop/Documentation/Arguments.md

**Comment by hmlongco** [comment]
Changes made to develop for this are now merged into Master.
