### ISSUE TITLE
Allow passing arguments via @Injected and @LazyInjected

### ISSUE THREAD

**Issue by smamczak** [hmlongco/Resolver#45]
Any chances to make this possible?

**Comment by hmlongco** [comment]
The develop branch has been updated with changes to the [argument passing mechanism in Resolver](https://github.com/hmlongco/Resolver/blob/develop/Documentation/Arguments.md). (Make sure you switch to the develop branch.)

That said, I haven't made any changes to the property wrappers yet. If I do, however, it probably would only be to LazyInjected. 

Injected is instantiated immediately along with the rest of the object's properties prior to init() being called, so the only thing you could pass to it would be fixed constants and not variables.

**Comment by smamczak** [comment]
Hi, you are right. It makes sense only for @LazyInjected. Looking forward to the update.

I checked your code. Why don't you use variadic parameters fo passing multiple args? Less code and work in my opinion

**Comment by hmlongco** [comment]
See edited comment above.

**Comment by hmlongco** [comment]
Considered variadic parameters, but I wanted to reinforce the 1-to-1 relationship between the args passed and the args consumed in the factory. (arg0 = arg[0], arg1 = arg[1]

```
register { (_ args) in ABC(name: args[0]!) }

let abc: ABC = Resolver.resolve(arg0: "fred")
```
With variadics getting the order wrong would be even easier.

Still wondering if I should switch to a dictionary instead.
```
register { (_ args) in ABC(name: args["name"]!) }

let abc: ABC = Resolver.resolve(args: ["name": "fred"])
```

**Comment by smamczak** [comment]
Dictionary is more deterministic in my opinion.

In current stage of @propertyWrappers I see there is no way to call self and access class instance. Maybe they will change it in the future, but for now it looks like there is nothing we can do.

**Comment by hmlongco** [comment]
Check out the develop branch for 1.2. There's actually a way to pass arguments thru @LazyInjected.

https://github.com/hmlongco/Resolver/blob/develop/Documentation/Arguments.md

**Comment by smamczak** [comment]
Great! Thanks a lot!

**Comment by doozMen** [comment]
Hei I really love the good and considered way this project is build and how you discussed arguments here. I hope to contribute to the discussion. I will make an MR and reference it here for the arguments. I made it from master before I read this and now see that my solution is not optimal and I might need to reconsider. 
But one thing I noticed while playing around is that when you register for a Type 2 ways to inject it with property wrappers you would, one with and one without arguments you would expect them to resolve differently, but they do not. I tried to clarify that in an MR. Please let me know what you think. Thanks

**Comment by hmlongco** [comment]
As mentioned above, argument passing was updated for 1.2, but not for property wrappers.
