### ISSUE TITLE
Implement Resolver across a multi-module application?

### ISSUE THREAD

**Issue by bluejarapp** [hmlongco/Resolver#48]
First, thanks for Resolver -- it's been a great service for me. But now I'm refactoring my project from a monolith to a modular model where all the modules are frameworks, except for the root application module.

I haven't been able to make Resolver work across more than one module, and I've tried various strategies -- putting an AppDelegate+Injection inside each module, using one AppDelegate+Injection file and importing modules with individual +Injection files, importing a module and registering its classes inside the host module. It doesn't matter whether I'm working in a framework module or the application module -- anything that crosses the boundaries of a single module breaks with a service not resolved error.

Are there any plans to implement Resolver across modules, or am I just doing it wrong?

**Comment by aoathout** [comment]
We are using Resolver with Swift packages to keep things modular. We have been able to define and register services in different packages and resolve them in the main application without issue.

FeatureOne Swift Package, service protocol and implementation
`import Foundation

public protocol HelloService {
    func sayHello(name: String) -> String
}

public class SayHelloService: HelloService {
    public func sayHello(name: String) -> String {
        "Hello from FeatureOne: \(name)"
    }
}`

FeatureOne+Injectable.swift
`import Foundation
import Resolver

public extension Resolver {
    static func regiterFeatureOneServices() {
        register { SayHelloService() as HelloService }
    }
}`

Main Application:
`import Foundation
import Resolver
import FeatureOne

extension Resolver: ResolverRegistering {
    public static func registerAllServices() {
        regiterFeatureOneServices()
    }
}`

Usage:
`import SwiftUI
import Resolver
import FeatureOne

struct ContentView: View {
    private var helloService: HelloService = Resolver.resolve()
    
    var body: some View {
        Text(helloService.sayHello(name: "Aaron"))
    }
}`

Output:
Hello from FeatureOne: Aaron

Hope that helps.

**Comment by bluejarapp** [comment]
Thanks Aaron, I was able to do that, but what I'm talking about is having a global DI across the entire workspace so different modules can share the same dependencies. Which admittedly is somewhat of an antipattern, but I only want to share a small number of basic services needed globally, such as reading and writing from APIs and data stores. In fact, I'm barely using the main application at all except as a jumping off point. If it tells you anything I'm a Java dev who's used to the Spring model.

**Comment by hmlongco** [comment]
I've not done this but according to someone who did they put Resolver in a "shared" package that all of the other packages, including main, depended upon. That way all of the registrations and resolutions occurred based on the variables in the same package. Make sense?

**Comment by bluejarapp** [comment]
Hi Michael,

Apologies for the delayed response, I've been away.

Yes, your approach makes sense, but the peculiarities of my project don't make it possible for me to use it. I'm using the Firebase library, which, unlike Facebook and Google, can only be implemented in the main application. If there were a way I could install it on a standalone module and share it wherever needed it would be a joy. It's just a case of two frameworks that simply can't play with each other and I've unfortunately had to remove Resolver.

I appreciate the feedback though, and I'm looking forward to being able to use Resolver again instead of my jerry-rigged nonsense.

Thanks,
Mike
