### ISSUE TITLE
Swift package product 'Resolver' is linked as static library by 'XXXX' and 'YYYY'.

### ISSUE THREAD

**Issue by mobiletoly** [hmlongco/Resolver#51]
I have a project with few subprojects and while trying to add Resolver via SPM to both projects, getting this error:

--- Swift package product 'Resolver' is linked as static library by 'XXXX' and 'YYYY'. This will result in duplication of code ---

Do you think it makes sense to add

    type: .dynamic

to .library section in Package.swift file?

I know it is not really a Resolver issue, since there is ongoing thread here:
https://developer.apple.com/forums/thread/128806

where people discussing this issue (and as usual - without any help from Apple), but I think at least Resolve can fix it on its side.

**Comment by hmlongco** [comment]
I don't know. If you fork the project and add it does it fix the problem? Haven't really used SPM yet.

On Jul 7, 2020, at 5:40 AM, Toly Pochkin <notifications@github.com> wrote:


I have a project with few subprojects and while trying to add Resolver via SPM to both projects, getting this error:

--- Swift package product 'Resolver' is linked as static library by 'XXXX' and 'YYYY'. This will result in duplication of code ---

Do you think it makes sense to add

type: .dynamic
to .library section in Package.swift file?

**Comment by sthwicked** [comment]
Being a dependency injection framework it would make more sense for it to be linked dynamically rather than statically (so that containers can be shared across modules). SPM, however, has some serious issues when it comes to handling dynamic lib linking so I personally chose to integrate the framework manually as a dynamic framework

**Comment by hmlongco** [comment]
PR for this was merged into 1.2
