### ISSUE TITLE
On iOS 14 some of my dependencies are injected twice

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#53]
`        register { (resolve() as CoreDataStack).context }.scope(Resolver.application)`

<img width="430" alt="image" src="https://user-images.githubusercontent.com/55385694/87320917-783cd000-c523-11ea-9ab1-fa6940fe0150.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/55385694/87321066-a9b59b80-c523-11ea-8312-8f20d45c5f05.png">

**Comment by mac-cain13** [comment]
Think it would be helpful if you could provide a little more context or perhaps a small sample project that shows this behavior.

A comparable setup to your register is working fine for me. Also the stack traces just shows Resolver doing its work, not giving a clear indication of a double injection in any way to me.

**Comment by hmlongco** [comment]
Definitely not seeing this as Resolver is running in IOS 14 on all of our projects. Would need a test project or better example.
