### ISSUE TITLE
ResolverRegistration.cacheKey should include resolver hash?

### ISSUE THREAD

**Issue by lisacmer** [hmlongco/Resolver#63]
I wonder if based on your description of containers, a container should have its own cached instances of an application scope. Consider an example:
```
extension Resolver  {
    static let resolver1 = Resolver(parent: main)
    static let resolver2 = Resolver(parent: main)
    static func registerAll() {
        resolver1.register { UIStoryboard(name: "storyboard1", bundle: nil) }.scope(application)
        resolver2.register {
            // 2
            UIStoryboard(name: "storyboard2", bundle: nil)
        }.scope(application)
        resolver1.resolve() as UIStoryboard
        register { ((resolver2.resolve() as UIStoryboard).instantiateInitialViewController() as! VC2) }
    }
}
```
2 will never get executed unless we provide each Resolver instance with its own ResolverScopeApplication instance. Same thing will happen in your Containers example if the registrations will have the application scope. Is it intended design?

**Comment by hmlongco** [comment]
The primary concept behind the application scope is support for singletons. Allowing multiple instances violates that contract. Further, all scopes (not just application) are defined as static lets which places them in the same scope as most of the registration blocks.

```
extension Resolver: ResolverRegistering {
    public static func registerAllServices() {
        register { MyClass(resolve()) }.scope(application)
        register { NyService() }.scope(cached)
    }
}
```
Above, `resolve()` and `application` and `cached` are in the static class scope and as such don't need to be fully qualified. (e.g. Resolver.application).

That fits in with the "global" access and autowire philosophy used by much of Resolver, especially in cases like `@Injected`. Unlike some other DI systems, containers, while supported, are definitely second-class citizens and probably best used for special cases like unit testing.

Finally, it looks as if you're using containers primarily to support instantiating identical class types. If you need something like that I'd consider using named instances.
```
register(name: "sb1") { UIStoryboard(name: "storyboard1", bundle: nil) }.scope(application)
register(name: "sb2") { UIStoryboard(name: "storyboard2", bundle: nil) }.scope(application)

@Injected(name: "sb1") var storyboard: UIStoryboard
```
