### ISSUE TITLE
SwiftUI application with no AppDelegate or SceneDelegate

### ISSUE THREAD

**Issue by Prince2k3** [hmlongco/Resolver#64]
How can I get Resolver to work when there isn't an AppDelegate or SceneDelegate?

```Swift 

@main
struct HopApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

```Swift 
extension Resolver: ResolverRegistering {
    public static func registerAllServices() {
        registerServices()
    }
}
```

I have the registerAllService implemented but it doesn't get called.

**Comment by mac-cain13** [comment]
Your setup seems right and should work. I've just added Resolver to my SwiftUI application using the new `@main` annotation and no App or SceneDelegate. It all works as expected.

Are you requesting Resolver to solve a dependency? Resolver won't call `registerAllServices` until the first dependency needs to be resolved. This might be why you don't see a call to the `registerAllServices` method just yet.

**Comment by Prince2k3** [comment]
@mac-cain13 You are right... I forgot I opened this as it was a different issue with modular architecture that caused it not to work properly which I already resolved.

Thanks!
