### ISSUE TITLE
How to inject different types of doubles?

### ISSUE THREAD

**Issue by danielbmaranhao** [hmlongco/Resolver#69]
Hi there, 
First of all, thank you for making this library available to the community.

Going directly to my question, there’s some well-know way for injecting different types of test doubles for a given dependency?

In a test project, I was able to inject a spy using the Swift Compiler Custom Flags approach, but there’re some cases that we’d like to inject a stub instead. How we could do that?

Having a double that behaves like a stub and a spy at the same time is an option, but I'm wondering if there is a way to avoid that.

Here’s how my code is looking like now:
```swift
extension Resolver {
    
    static func registerMenuService() {
        let menuService: MenuService
        
        #if MOCK
            menuService = MenuServiceSpy()
        #else
            menuService = MenuGravyService()
        #endif
        
        register {
            menuService
        }
    }
}

class ViewControllerTests: XCTestCase {
    
    func testViewController_whenLoadsView_fetchesRestaurantData() throws {
        let viewController = ViewController()
        
        viewController.viewDidLoad()
        
        let menuServiceSpy = try XCTUnwrap(viewController.service as? MenuServiceSpy)

        XCTAssertTrue(menuServiceSpy.didFetchRestaurant)
    }
}
```

**Comment by marcmatta** [comment]
Hey @danielbmaranhao ,

This information is provided in [this](https://github.com/hmlongco/Resolver/blob/master/Documentation/Names.md#example-mocking-data) section of Named Instances

**Comment by danielbmaranhao** [comment]
Oh, cool! That’s new :D

Thanks, @marcmatta.

**Comment by hmlongco** [comment]
Using "enumerated" names is new. Named registrations based on string have been in Resolver since 1.0.
