### ISSUE TITLE
Reset cache issue

### ISSUE THREAD

**Issue by totidev** [hmlongco/Resolver#7]
If you add an item to the cached scope:
`resolver.register { XYZValue() }.scope(Resolver.cached)`
And then call:
`Resolver.cached.reset()`
The item is still returned when calling:
`let newService: XYZValue = resolver.optional()`

I would expect that the item is not returned in the last line, due to having reset the cache.

**Comment by hmlongco** [comment]
I added some more code to the unit test for caching so I could -check to see if the cache is being cleared correctly and it seems to do so.

```
    func testResolverScopeCached() {
        // Reset...
        Resolver.cached.reset()
        resolver.register { XYZSessionService() }.scope(Resolver.cached)
        let service1: XYZSessionService? = resolver.optional()
        let service2: XYZSessionService? = resolver.optional()
        XCTAssertNotNil(service1)
        XCTAssertNotNil(service2)
        var originalID: ObjectIdentifier!
        if let s1 = service1, let s2 = service2 {
            XCTAssert(s1.count == s2.count)
            let s1id = ObjectIdentifier(s1)
            let s2id = ObjectIdentifier(s2)
            XCTAssert(s1id == s2id)
            originalID = s1id
        } else {
            XCTFail("sessions not cached")
        }
        let oldCount = service1?.count ?? 0
        // Reset...
        Resolver.cached.reset()
        // ...and try again
        XCTAssert(Resolver.cached.isEmpty == true)
        if let newService: XYZSessionService = resolver.optional() {
            XCTAssert(newService.count > oldCount)
            let newid = ObjectIdentifier(newService)
            XCTAssert(originalID != newid)
        } else {
            XCTFail("newService not resolved")
        }
    }
```
Further, other than the mutex's involved in multi-threading, the cache code (and the cache clearing code) is pretty straightforward.

If you're seeing the above behavior in an app my first reaction would be that you have a retain or retain cycle on or in the object that has the `let newService: XYZValue` code and as such it's never being recreated and so it never needs to resolve a new instance.

**Comment by hmlongco** [comment]
Mmmm.... could be that I read too much into your original post and that it's a simple misunderstanding of how the cached scope works.

1) If you try to resolve an object and it's not in the cache, it creates one AND caches it.

2) If you try to resolve an object and it IS in the cache, it returns the cached object.

3) If you clear the cache, then try to resolve an object, you're basically back in the first state. It looks, it's not there, so it makes a new one and returns it.

The goal is to always resolve to an object. Caching, shared, etc., just controls whether or not you get a new object or one previously created.

**Comment by totidev** [comment]
Yes, thanks, that does explain it. Is there a way to remove an item completely, so that you would need to add it again?

**Comment by hmlongco** [comment]
The service isn't instantiated until it needs to be resolved, so it's "built" at that point in time by calling the factory closure registered for that object. If the service was cached, you get the same instance. If you clear the cache, you get a new instance on the very next resolution.

Bottom line, clear the cache and you'll get a "new" object on the next resolution.

That said, if you call register again with the same type signature you'll replace the factory for that signature with the new factory closure.
