### ISSUE TITLE
`registrations` is not thread safe

### ISSUE THREAD

**Issue by zhihuitang** [hmlongco/Resolver#70]
![image](https://user-images.githubusercontent.com/5066926/93458902-38a6b180-f8e1-11ea-9f01-3f870ef2f120.png)

I reckon it is becaue the variable `registrations` of **Resolver.swift** is not thread-safe and there is no Mutex when write/read it.
Imaging `register` and `resolve` are called simultaneously from different threads, data race issue might happen.

```
private var registrations = [Int : [String : Any]]()

//...
public final func register<Service>(_ type: Service.Type = Service.self, name: String? = nil,
                                        factory: @escaping ResolverFactoryArguments<Service>) -> ResolverOptions<Service> {
        let key = ObjectIdentifier(Service.self).hashValue
        let registration = ResolverRegistration(resolver: self, key: key, name: name, factory: factory)
        if var container = registrations[key] {
            container[name ?? NONAME] = registration
            registrations[key] = container
        } else {
            registrations[key] = [name ?? NONAME : registration]
        }
        return registration
    }
```

**Comment by zhihuitang** [comment]
I do find the data race issue:
![image](https://user-images.githubusercontent.com/5066926/93461163-a99b9880-f8e4-11ea-8c39-8aa3100fc6b3.png)
![image](https://user-images.githubusercontent.com/5066926/93461223-bf10c280-f8e4-11ea-891f-d7340306f781.png)

**Comment by hmlongco** [comment]
Added this to PR, but here as well. See discussion on threading in documentation: https://github.com/hmlongco/Resolver/blob/master/Documentation/Threads.md

I'm not sure I want to add a performance hit on all accesses to registrations. We can discuss.

**Comment by hmlongco** [comment]
Checkout the develop branch for Resolver version 1.4. The locking strategies and mechanisms have been completely overhauled.
