### ISSUE TITLE
[Help] Override class in UI Tests

### ISSUE THREAD

**Issue by bfrolicher** [hmlongco/Resolver#76]
Hi,

It's seem that it is not possible to override some class in unitTest or UITest target;

For unit test, I can workaround this by removing the hosted app, but how can I do that for UITest without adding some ENV variable to the main application.

Main app : 

```swift
extension Resolver: ResolverRegistering {
    public static func registerAllServices() {
        register { PersonAPI() as PersonAPIProtocol }.scope(application)
    }
}
```

UITest target : 

```swift
let tu = Resolver(parent: .main)
tu.register { TUPersonAPI() as PersonAPIProtocol }.scope(Resolver.application)
Resolver.root = tu
let api = Resolver.resolve(PersonAPIProtocol.self, name: nil, args: nil)
///  api is TUPersonAPI instance => OK  
let app = XCUIApplication()
app.launch()
```

```swift
class ViewModel {
    @Injected var api: PersonAPIProtocol
    
    func fetch(completion: @escaping ([Person]) -> ()) {
        
        self.api.fetchPersons { (persons) in
            completion(persons)
        }
    }
}
```

But when launching UI test api is an PersonAPI instance in viewModel

Do apps and tests have a completely different context ?
Ben

**Comment by hmlongco** [comment]
I'm working on how to better use Resolver in unit tests. Stay tuned.

**Comment by lazyvar** [comment]
This isn't the answer to OP's original question, but for anyone else curious on how to do testing specifically with the `@Injected` tag, here is an idea that does not involve checks for a testing flag in main app code:

```swift
import Resolver

extension Resolver {
  static var mocks = Resolver(parent: main)

  static func setupMocking(_ mockingBlock: (Resolver) -> Void) {
    mockingBlock(mocks)
    root = mocks
  }

  static func resetMocks() {
    mocks = Resolver(parent: main)
  }
}
```
```swift
func viewModelTest() {
  Resolver.setupMocking { mocks in
    mocks.register { ServiceClass() }
  }

  let viewModel = ViewModel() // services magically instantiated to mocked version

  // ... tests

  Resolver.resetMocks() // clean up
}
```
It seems the downside to using `@Injected` vs constructor injection is testing is more cumbersome as it's not as explicit what services a class needs and there needs to be some clean up to global state before or after every test. Not too bad a tradeoff for a pretty sweet property wrapper. Interestingly when searching all of GitHub for apps that use `Resolver` and `@Injected`, none had tests. And when searching for apps that used `Resolver` and had tests, none used `@Injected`.

Looking forward to what you come up with @hmlongco ! Awesome library.

**Comment by hmlongco** [comment]
@lazyvar That's basically it. The "main" container will have everything your app has already defined and needs. You're just locally defining any mock dependencies needed for what you're testing.

You could also make your life a bit easier if the mock setup function added anything that tended to be consistently needed across most of your test cases.
```swift
extension Resolver {
  static func setupMocking(_ mockingBlock: (Resolver) -> Void) {
    mocks.register { MockUser() as CurrentUserProvider }
    mockingBlock(mocks)
    root = mocks
  }
```
Also keep in mind that you can "reregister" classes and that they will replace existing registrations. As such there may not be a need to setup and tear down *everything* during a given test run.
```swift
func testA() {
     Resolver.mock.register { MockUserA() as CurrentUserProvider }
     let model: ViewModel = Resolver.resolve()
     // do some tests on model
}

func testB() {
     Resolver.mock.register { MockUserB() as CurrentUserProvider }
     let model: ViewModel = Resolver.resolve()
     // do some tests on model
}
```

**Comment by hmlongco** [comment]
I've build a small demo app that illustrates unit testing with Resolver.

https://github.com/hmlongco/Builder
