### ISSUE TITLE
ViewModels as scope shared still keeps its values.

### ISSUE THREAD

**Issue by Prince2k3** [hmlongco/Resolver#77]
I came across this closed issue response and I thought alright that is the way I should go when dealing with StateObject types in SwiftUI. I then started running into another issue. If I keep the scope(shared) then all of the data dealing with that view model keeps being retained. What I am looking for is away to get passed the StateObject issue and have the view model init when the view is also init.

```
Should also note that to use it properly with SwiftUI views you probably want your view models to be .scope(shared)

Also, thanks for using Resolver.

_Originally posted by @hmlongco in https://github.com/hmlongco/Resolver/issues/68#issuecomment-687679447_
```

**Comment by beeirl** [comment]
hey @Prince2k3 have you found a solution for this?

**Comment by Prince2k3** [comment]
I removed the shared scope from my view model. Then made mine own property wrapper that uses StateObject instead of ObservedObject by copying InjectedObject code and doing the replacement. I haven't had a problem since.

**Comment by beeirl** [comment]
@Prince2k3 thanks for getting back to me man! Appreciate it. It didn't solve my problem unfortunately :/ Still fighting with this [issue](https://github.com/hmlongco/Resolver/issues/90)
