### ISSUE TITLE
@Injected Property Wrapper

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#8]
Just read your excellent post on [how to use Swift 5.1 Property Wrappers to cut your dependency injection code in half.](https://medium.com/better-programming/taking-swift-dependency-injection-to-the-next-level-b71114c6a9c6).

Why not include the `@Injected` property wrapper in this project?

**Comment by hmlongco** [comment]
I was waiting for Xcode 11 and Swift 5.1 to finalize. It has, and I've added it to the project and wrapping up the changes to the documentation now. Should drop sometime this week.

**Comment by mycroftcanner** [comment]
It would be cool as well if @Injected could support names.

**Comment by hmlongco** [comment]
Names and containers. See: https://github.com/hmlongco/Resolver/blob/develop/Documentation/Annotation.md

**Comment by mycroftcanner** [comment]
Amazing!

**Comment by ahmadmssm** [comment]
@hmlongco Can not use it with xcode 11.1, do you have any idea, thanks in advance
