### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by benben28405678** [hmlongco/Resolver#80]
In _Resolver.swift_, there is a spelling issue on line `221`.

Source code:
`fatalError("RESOLVER: '\(Service.self):\(name ?? "")' not resolved. To disambiguate optionals use resover.optional().")`

The issue:
`resover.optional()` -> `resolver.optional()`

Spell-corrected code:
`fatalError("RESOLVER: '\(Service.self):\(name ?? "")' not resolved. To disambiguate optionals use resolver.optional().")`

**Comment by hmlongco** [comment]
Thanks.
