### ISSUE TITLE
Fatal Error: FIRFirestore not resolving

### ISSUE THREAD

**Issue by hferrone** [hmlongco/Resolver#88]
Hi!

I'm having a problem using Resolver in my iOS + Firebase project. When I run my app, I get the following error:

Fatal error: RESOLVER: 'FIRFirestore:' not resolved. To disambiguate optionals use resolver.optional().: file Resolver/Resolver.swift, line 222.

I've read your docs on optionals, and I don't have any in my project that relate to the services I've registered:

<img width="562" alt="Screen Shot 2021-01-18 at 9 30 35 PM" src="https://user-images.githubusercontent.com/8218795/104988281-f0091d00-59d4-11eb-92d2-0b54d0ef58ac.png">
<img width="548" alt="Screen Shot 2021-01-18 at 9 31 25 PM" src="https://user-images.githubusercontent.com/8218795/104988282-f0a1b380-59d4-11eb-9b7c-80918a43fa70.png">
<img width="662" alt="Screen Shot 2021-01-18 at 9 31 34 PM" src="https://user-images.githubusercontent.com/8218795/104988284-f0a1b380-59d4-11eb-8e8f-a1bd7b653315.png">

For reference, I've been following this wonderful tutorial by someone who works at Firebase: https://peterfriese.dev/replicating-reminder-swiftui-firebase-part2/

I'm not sure if I'm just misunderstanding the way injected variables work, or how DI files are resolved behind the scenes. Any help would be greatly appreciate!

Cheers,

Harrison Ferrone

**Comment by hmlongco** [comment]
Attempting to use resolve() on an optional is a common problem, which is why it's mentioned.

At first glance, it looks like you registered FirestoreRepository and SessionStore, but in the repository you're also injecting db: Firestore but I'm not seeing a registration for that. Everything you attempt to inject or resolve must be registered.
