### ISSUE TITLE
Why is AppDelegate+Injection.swift called like that?

### ISSUE THREAD

**Issue by mycroftcanner** [hmlongco/Resolver#9]
What is the rationale behind naming `AppDelegate+Injection.swift` like that?

The extension doesn't apply to AppDelegate and these days AppDelegate may not be the starting point of an app anymore.

**Comment by hmlongco** [comment]
That was a bit of a carryover from SwinjectStoryboard, the first DI system we used on a project. 

In Swinject you'd group the injections for a feature into a file named "feature+Swinject.swift". The routine to call all of the various registration blocks existed in "AppDelegate+Swinject.swift".

Checkout SwinjectStoryboard for more.
