### ISSUE TITLE
registerAllServices method is not called in the main project

### ISSUE THREAD

**Issue by sanyesz123** [hmlongco/Resolver#91]
**Setup**

I have an iOS application target which uses **Resolver 1.4.0**. I also have a cocoa touch framework target using Resolver too. The framework is embedded in the main application's bundle. The Resolver framework is pulled into the project via Cocoapods, and it is shared through an abstract target in the Podfile. 

**Resolver registrations**

Both targets have their own Resolver extensions for registering the dependencies. 

```
import Resolver

extension Resolver: ResolverRegistering {
    public static func registerAllServices() {
        ...
    }
}

```

**The problem**

The compiler can compile both targets, the application's bundle is created successfully and looks good. A strange behaviour happens only on iOS 12.X simulators (on real devices, and on simulators with later iOS versions everything is working fine): when the application is started the **registerAllServices** **static method** is called from the framework and not from the main application target (even if the framework is not imported in the code), so the application won't register its classes and it crashes during the first injection. 

References related to problem: 

- https://stackoverflow.com/questions/48762971/swift-protocol-conformance-by-extension-between-frameworks/51391793#51391793
- https://bugs.swift.org/browse/SR-3908
- https://medium.com/flawless-app-stories/static-vs-dynamic-dispatch-in-swift-a-decisive-choice-cece1e872d

**Sample project**

[ResolverExample.zip](https://github.com/hmlongco/Resolver/files/6042912/ResolverExample.zip)

**Question**

Do you have any options / ideas how to handle this case?

**Comment by sanyesz123** [comment]
Update: seems the problem is present on some iOS 12.x real devices too.

**Comment by hmlongco** [comment]
I'm not sure if this covers everything, but the following project repository demonstrates using Resolver across frameworks and in the main application.

https://github.com/hmlongco/ResolverFrameworksTest

This may not be an exact parallel, but it may help you get to where you need to be.
