### ISSUE TITLE
Possible error in documentation (`XYZService` and `XYZCombinedService`)

### ISSUE THREAD

**Issue by phi161** [hmlongco/Resolver#94]
First of all, thank you for this great library and for the effort to provide detailed Documentation, I find it extremely helpful!

In [this section](https://github.com/hmlongco/Resolver/blob/master/Documentation/Introduction.md#viewcontrollers-viewmodel-and-services-oh-my) of the Introduction, the docs say:

> The XYZService, in turn, needs a reference to an XYZSessionService to do its job.

but later in the code sample:

```
class XYZCombinedService: XYZFetching, XYZUpdating {
    private var session: XYZSessionService
    init(_ session: XYZSessionService) {
        self.session = session
    }
    // Implmentation
}

struct XYZService {
    // Implmentation
}
```

Am I missing something here, or `XYZViewModel` should depend on `XYZCombinedService` instead of `XYZService`?

**Comment by hmlongco** [comment]
Did a quick update to the documentation.

The XYZViewModel needs an instance of an object that implements a XYZFetching protocol, one that implements XYZUpdating, and the view model also wants access to a XYZService for good measure.

So XYZViewModel wants references to three objects. But in our code, XYZCombinedService implements *both* the XYZFetching and the XYZUpdating protocols *in the same class*. Not to mention that XYZCombinedService also *has its own dependency*, and needs a reference to an XYZSessionService to do its job.

The code makes those dependencies clear.

**Comment by phi161** [comment]
I understand now! Thanks a lot for the prompt reply!
