### ISSUE TITLE
Dead lock in 1.4.0

### ISSUE THREAD

**Issue by zhihuitang** [hmlongco/Resolver#95]
In Resolver 1.4.0, when I try to resolve a dependency, it get stuck at `lock.lock()`, it seems it get dead lock here.
But it worked very well in 1.3.0. Please kindly have a look, thank you.

![image](https://user-images.githubusercontent.com/5066926/110309913-3573bf00-8002-11eb-9596-1edabc4c6c12.png)

**Comment by hmlongco** [comment]
Actually, there were cases in 1.3 where it actually failed to lock when needed. 1.4 fixed that.

As to the deadlock, there's not enough information here for me to attempt to debug this. I suggest looking at the stack trace to see if you can determine where and under what circumstances you might be deadlocking.

**Comment by hmlongco** [comment]
No response so closing.
